


TARGET = libbzip2.a
DEFS =  -DDREAMCAST

all: $(TARGET)

include $(KOS_BASE)/Makefile.rules

OBJS = \
	blocksort.o \
	bzlib.o \
	compress.o \
	crctable.o \
	decompress.o \
	huffman.o \
	randtable.o

clean:
	rm -f $(OBJS)

$(TARGET) : $(OBJS)
	rm -f $(KOS_BASE)/addons/lib/dreamcast/$(TARGET)
	$(KOS_AR) rcs $(KOS_BASE)/addons/lib/dreamcast/$(TARGET) $(OBJS)
	$(KOS_RANLIB) $(KOS_BASE)/addons/lib/dreamcast/$(TARGET)
	cp bzlib.h $(KOS_BASE)/addons/include/
